name: LittleKiwiBus
markdown: redcarpet
excerpt_separator: <!--more-->
paginate: 3
paginate_path: "/blog/page:num/"
highlighter: pygments
plugins: [jekyll-paginate, jekyll-gallery-generator]
disqus: littlekiwibus
background1: "#F4F7F0"
secondcolor: "#9ccc66"
navhovercolor: #000000
font: 'font-family: "Nunito", sans-serif;'
footercolor: "#F4F7F0"
buttoncolor: "#F4F7F0"
buttontextcolor: "#646569"
buttonhovercolor: "#9ccc66"
buttonbordercolor: "#646569"
worksoverlaycolor: "#f6f6f6"
linktextcolor: "#646569"
linktexthovercolor: "#9ccc66"
stephs-bg: "#F4F7F0"
scotts-grey: "#646569"
captiontextcolor: "#000000"

plugins:
  - jekyll-gallery-generator
  - jekyll-paginate

# #jekyll-gallery-generator
gallery:
  dir: gallery               # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Gallery"           # Title for gallery index page
  title_prefix: "Gallery: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 200                # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    Measurement-Photos:
      best_image: DSC_5462.jpg  # The image to show on the gallery index page. Defaults to the last image.
      name: "Measurement Photos"  
      # dir: Measurement-Photos
    Picking-Up-Our-Bus:
      best_image: IMG_0090.JPG  # The image to show on the gallery index page. Defaults to the last image.
      name: "Picking Up Our Bus"  
      # dir: Picking-Up-Our-Bus      
    with_info:
      info:
        desc: "Gallery Description" # Info fields can be used in custom templates.