name: LittleKiwiBus
markdown: redcarpet
excerpt_separator: <!--more-->
paginate: 3
paginate_path: "/blog/page:num/"
highlighter: pygments
gems: [jekyll-paginate]
disqus: littlekiwibus
background1: "#F4F7F0"
secondcolor: "#9ccc66"
navhovercolor: #000000
font: 'font-family: "Nunito", sans-serif;'
footercolor: "#F4F7F0"
buttoncolor: "#F4F7F0"
buttontextcolor: "#646569"
buttonhovercolor: "#9ccc66"
buttonbordercolor: "#646569"
worksoverlaycolor: "#f6f6f6"
linktextcolor: "#646569"
linktexthovercolor: "#9ccc66"
stephs-bg: "#F4F7F0"
scotts-grey: "#646569"
captiontextcolor: "#000000"